gms:
  server:
    change_emblem_cost: 5000000
    enable_pin: false
    timeout_duration: 3600000
    dojo_energy_dmg: 20
    mob_damage_mob_max_damage_rate: 1.5
    family_rep_per_level_up: 200
    use_stack_coupon_rates: false
    use_multiple_same_equip_drop: true
    enable_pic: false
    mob_status_monitor_proc: 200
    expand_guild_tier_cost: 1000000
    expand_guild_base_cost: 5000000
    use_erase_untradeable_drop: true
    use_item_sort: true
    allow_steal_quest_item: true
    family_rep_per_kill: 4
    use_equipment_level_up_slots: false
    battleship_stance: 30
    use_auto_ban: false
    use_ultra_three_snails: false
    mob_spawnrate_max_players: 6
    use_max_range_echo_of_hero: true
    npcs_scriptable:
      1300005: 蘑菇王国
      9001105: Rescue Gaga!
    party_search_reentry_limit: 10
    bypass_pic_expiration: 20
    allow_cash_shop_world_transfer: true
    use_buff_everlasting: false
    use_fast_dojo_upgrade: false
    use_starting_ap_4: false
    use_joint_cash_shop_inventory: false
    use_enable_party_level_limit_lift: false
    name_change_cooldown: 2592000000
    max_channel_size: 20
    cygnus_max_level_cap: 155
    max_monitored_buff_stats: 5
    use_maker_fee_heuristics: true
    collective_chr_slot: true
    use_announce_change_job: false
    pets_never_hungry: false
    create_guild_cost: 10000000
    equip_godly_max_bonus: 5
    use_fishing_system: false
    summon_max_damage_rate: 1.5
    use_quest_rate: true
    use_announce_nx_coupon_loot: false
    playernpc_auto_deploy: true
    damage_hack_point_ratio: !!float '5'
    pet_exhaust_count: 3
    wedding_bless_exp: 30000
    use_refresh_rank_move: true
    use_add_slots_by_level: true
    use_equipment_level_up_continuous: false
    wedding_reservation_interval: 20
    use_enforce_item_suggestion: false
    use_unit_price_with_comma: true
    use_buff_most_significant: true
    enable_knights_of_cygnus: false
    use_supply_rate_coupons: false
    wedding_reservation_timeout: 10
    chaos_scroll_stat_range: 6
    use_maker_permissive_atk_up: false
    use_exp_gain_log: false
    use_server_auto_pot: false
    chaos_scroll_stat_rate: 1
    use_autosave: true
    family_max_generations: 1000
    playernpc_initial_y: 262
    pq_bonus_exp_rate: 0.5
    playernpc_initial_x: 262
    mob_spawn_base_rate: 0.7
    pet_auto_hp_ratio: 0.99
    use_npcs_scriptable: true
    item_monitor_time: 300000
    marksman_blind_stance: 100
    max_allowed_account_hwid: 10
    detect_reward_nx: 10000
    rebirth_npc_id: 9010021
    use_lk_clean_slate: true
    use_party_for_starters: false
    use_debug_show_rcvd_packet: false
    max_recall_time: 2
    max_level_cap: 200
    change_channel_force_return: false
    use_auto_ban_log: true
    trade_limit_meso_max: 1000000
    channel_capacity: 100
    use_full_holy_symbol: false
    use_fixed_ratio_hpmp_update: false
    update_interval: 777
    use_starter_merge: false
    playernpc_organize_area: true
    wedding_gift_limit: 1
    quest_point_requirement: 0
    use_player_detect: false
    enable_the_lord_of_war: false
    level_up_sp_gain: 3
    max_world_size: 21
    use_elemental_weapon_gms_levelup: false
    exp_split_mvp_mod: 0.2
    minimum_gm_level_to_trade: 4
    use_map_ownership_system: true
    use_chair_extra_heal: false
    use_spawn_loot_on_animation: false
    equip_exp_rate: 2.0
    fast_reuse_hero_will_divisor: 60
    map_damage_overtime_interval: 5000
    mana_reflection_stance: 30
    use_rebirth_system: false
    use_enable_recall_event: true
    use_storage_item_sort: true
    boss_respawn_mob_time_rate: 1.0
    use_spikes_avoid_banish: false
    use_enhanced_chaos_scroll: false
    minimum_gm_level_to_use_storage: 4
    use_undispel_holy_shield: false
    mob_status_aggro_persistence: 2
    bypass_pin_expiration: 15
    use_erase_pet_on_expiration: false
    wedding_blesser_showfx: true
    use_ultra_recovery: false
    use_equipment_level_up_power: false
    use_enable_stage_skip: false
    marksman_snipe_damage: 195000
    max_equipment_level_up_stat_up: 10000
    aran_combo_gm_bonus: 5
    scroll_chance_rolls: 1
    minimum_gm_level_to_drop: 4
    use_quest_hp_pill: false
    use_announce_shop_item_sold: false
    use_ip_validation: false
    automatic_register: true
    mount_exhaust_count: 1
    exp_split_level_interval: 5
    trade_limit_item_nodrop: false
    map_damage_overtime_count: 2
    max_account_login_attempt: 15
    login_attempt_duration: 120000
    event_max_guild_queue: 10
    show_coupon_buff: true
    level_up_ap_gain: 5
    item_expire_check: 10000
    use_debug_show_life_move: false
    item_slot_max: 800
    damage_hack_severe_points: 15
    battleship_hp_per_level: 1200
    use_perfect_gm_scroll: true
    use_auto_hide_gm: true
    world_transfer_cooldown: 2592000000
    item_limit_on_map: 200
    use_custom_keyset: false
    use_character_account_check: false
    quest_point_per_quest_complete: 0
    playernpc_area_y: 160
    playernpc_area_x: 320
    trade_limit_meso_under_level: 15
    use_enforce_merchant_save: true
    use_enforce_unmerchable_cash: true
    damage_hack_alert_ratio: 1.5
    no_password: false
    use_debug_show_eqp_exp: false
    use_randomize_hpmp_gain: true
    use_fast_reuse_hero_will: true
    use_family_system: true
    recall_cooldown: 10
    use_equipment_gender_limit: false
    use_deadly_dojo: true
    exp_split_leech_interval: 5
    battleship_hp_per_skill_level: 3000
    use_equipment_level_up_vicious_levelrange_chance: '[[0,129,0.3],[130,255,0.9]]'
    map_visited_size: 5
    max_ap: 32767
    use_item_sort_by_name: false
    use_add_rates_by_level: false
    mob_spawnrate_to_player_count: 0.1
    use_old_gms_styled_pq_npcs: true
    use_wz_map_mob_rate: true
    detect_answer_seconds: 15
    minimum_gm_level_to_use_duey: 4
    event_lobby_delay: 10
    use_whole_server_ranking: false
    use_enable_solo_expeditions: false
    item_expire_time: 180000
    use_enforce_hpmp_swap: false
    use_anti_immunity_crash: true
    use_enable_custom_npc_script: false
    use_erase_permit_on_open_shop: true
    detect_jail_minutes: 60
    use_banishable_town_scroll: false
    use_login_notification: false
    use_debug: false
    instant_name_change: false
    use_enforce_unmerchable_pet: true
    playernpc_area_steps: 4
    use_enforce_novice_exp_rate: true
    mob_status_monitor_idle: 84
    quest_point_per_event_clear: 0
    aran_combo_last_time: 6
    use_equipment_level_up: 6
    damage_ranking: false
    use_announce_global_level_up: false
    use_beidou_beginner_map: false
    use_equip_growth_level_limit: true
    expand_guild_max_cost: 20000000
    use_perfect_scrolling: false
    tot_mob_quest_requirement: 0
    mob_status_aggro_interval: 5000
    block_npc_race_condition: 500
    equip_stat_randomize_range: 5
    use_duey: false
    wedding_reservation_delay: 3
    kite_expire_time: 3600000
    max_equipment_stat: 32767
    bcrypt_migration: true
    enable_adventurers: true
    pet_auto_mp_ratio: 0.99
    use_enhanced_crafting: false
    use_auto_aggro_nearby: false
    party_bonus_exp_rate: 1.0
    dojo_energy_atk: 100
    use_enforce_job_level_range: false
    use_enforce_mystic_door_position: false
    deterred_multi_client: false
    use_equipment_level_up_vicious: false
    exp_split_common_mod: 0.8
    deterred_player_command: false
    use_debug_show_packet: false
    use_perfect_pitch: false
    block_generate_cash_item: false
    use_server_auto_assigner: false
    channel_locks: 20
    use_equipment_level_up_cash: false
    use_mts: false
    timezone: GMT+8
    damage_hack_severe_ratio: !!float '30'
    use_full_aran_skill_set: false
    use_auto_assign_starters_ap: true
    use_enforce_admin_account: false
    system_rescue_maperror_changeid: 910000000
    create_guild_min_partners: 3
    use_ultra_nimble_feet: false
    use_cpq: true
    use_spawn_relevant_loot: true
    use_auto_assign_secondary_cap: true
    gm_pets_never_hungry: true
    use_compulsory_auto_pot: false
    family_rep_per_boss_kill: 20
    quest_point_repeatable_interval: 25
    mob_spawn_point_capacity: 2
    detect_cost_nx: 1500
    use_enable_daily_expeditions: true
    use_enforce_job_sp_range: false
    use_level_up_protect: true
    allow_cash_shop_name_change: true
    use_enable_full_respawn: false
    max_event_levels: 8
    mob_respawn_rate: 1
    respawn_interval: 2000
    use_enforce_mob_level_range: true
    use_max_range: true
    trade_limit_item_cash: false
    merchant_expire_time: 7
    use_gm_no_skill_cooldown: true
    use_enable_chat_log: true
  world:
    worlds:
    - flag: 0
      recommend_message: 欢迎来到枫之大陆！
      fishing_rate: 10.0
      quest_rate: !!float '1.25'
      meso_rate: !!float '2'
      level_exp_rate: !!float '0'
      server_message: ""
      quick_level_rate: !!float '0'
      quick_level: 0
      world_name: 枫之大陆MapleLand
      drop_rate: !!float '2'
      exp_rate: !!float '4'
      channel_size: 3
      travel_rate: !!float '5'
      boss_drop_rate: !!float '2'
      event_message: 枫之大陆
